[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
  
[[plugins]]
  package = "@netlify/plugin-bundle-analyzer"
  
[build.environment]
  SYSTEM_PACKAGE_LIBVIP = "libvips-dev"
